#ifndef TINYFS_ERRNO_H
#define TINYFS_ERRNO_H

#define FILE_BAD_DESCRIPTOR -1
#define NO_SPACE_LEFT -2
#define FS_CREATION_ERROR -3
#define FS_MOUNT_ERROR -4
#define FS_UNMOUNT_ERROR -5
#define FILE_OPEN_ERROR -6
#define FILE_CLOSE_ERROR -7
#define FILE_DELETE_ERROR -8
#define DEALLOCATION_ERROR -9
#define FILE_READ_ERROR -10
#define FILE_WRITE_ERROR -11
#define BLOCK_READ_ERROR -12
#define FILE_RENAME_ERROR -13
#define MEM_ALLOC_FAILURE -14

#endif
